name: NucleusWPF.MVVM

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Generate API metadata
        run: docfx metadata

      - name: Build documentation
        run: docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
